const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],TE=new TextEncoder(),TD=new TextDecoder(),LK='b26.v4.local',CK='budget2026.githubsync.config';
let app=null,pass='',edit=null,filters={owner:'Tous',type:'Tous',q:''},tmr=null;
const F={
"Salaire Romain (net sans 13ème mois / avant impots)":["(brutAnnuel/12)*0.75*(1-(0.75/100))-18*9*(40/100)-110",{brutAnnuel:52800}],
"Salaire Laura (net sans 13ème mois / avant impots)":["(brutAnnuel/12)*0.77*(1-(0.61/100))-18*8.5*(40/100)",{brutAnnuel:44262}],
"Tickets Restaurant Romain":["9*(60/100)*18",{}],
"Tickets Restaurant Laura":["9.5*18*(60/100)",{}],
"Crédit d’impôt de 1750€ Assmat mensualisé":["1750/12",{}],
"Crédit d’impôt 50% Kangourou Kids mensualisé":["1202/12",{}],
"Impôts Romain":["ligne('Salaire Romain (net sans 13ème mois / avant impots)')*tauxImpots",{tauxImpots:.06}],
"Impôts Laura":["ligne('Salaire Laura (net sans 13ème mois / avant impots)')*tauxImpots",{tauxImpots:.017}],
"Fioul mensualisé":["2500/12",{}],
"Charge de copro":["(130*4)/12",{}],
"Expert Comptable":["425/12",{}],
"Taxe foncière (Impots) mensualisée":["327/12",{}],
"MAM Rachel":["598+4*4.21*4.5",{}],
"Vacances et wkds : booking, transports, essence, péage, sur place":["5000/12",{}]
};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v){return typeof v=='number'?v:Number(String(v??'').replace(/\s/g,'').replace(',','.'))||0}
function eur(v){return(Number(v)||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:2})}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))),ub=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function k(p,s){let base=await crypto.subtle.importKey('raw',TE.encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:220000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function enc(o,p){let salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await k(p,salt),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,TE.encode(JSON.stringify(o)));return{format:'budget-2026-v4',salt:b64(salt),iv:b64(iv),ciphertext:b64(ct),updatedAt:new Date().toISOString()}}
async function dec(v,p){let key=await k(p,ub(v.salt)),raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:ub(v.iv)},key,ub(v.ciphertext));return JSON.parse(TD.decode(raw))}
function enrich(r){let a=F[r.label];return{...r,id:r.id||crypto.randomUUID?.()||Math.random().toString(36),frequency:r.frequency||'monthly',formula:r.formula||a?.[0]||'',variables:r.variables||a?.[1]||{},note:r.note||''}}
function fresh(){return{version:'v4',active:'Référence',scenarios:{'Référence':{createdAt:new Date().toISOString(),transactions:(window.INITIAL_DATA?.transactions||[]).map(enrich)}}}}
function rows(){return app.scenarios[app.active].transactions}
function cfg(){return{owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main',path:$('#path').value.trim()||'data/vault.json',token:$('#token').value.trim()}}
function loadCfg(){try{let c=JSON.parse(localStorage.getItem(CK)||'{}');for(let k of ['owner','repo','branch','path','token'])if(c[k]&&$('#'+k))$('#'+k).value=c[k]}catch(e){}}
function saveCfg(){localStorage.setItem(CK,JSON.stringify(cfg()))}
function msg(t){$('#msg').textContent=t||''} function state(t){$('#state').textContent=t}
async function saveLocal(){if(!app||!pass)return;localStorage.setItem(LK,JSON.stringify(await enc(app,pass)));$('#saveState').textContent='Sauvé '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function auto(){clearTimeout(tmr);$('#saveState').textContent='Sauvegarde...';tmr=setTimeout(saveLocal,350)}
async function start(){pass=$('#pass').value;if(!pass)return msg('Mot de passe requis');let raw=localStorage.getItem(LK);if(raw){try{app=await dec(JSON.parse(raw),pass);open('Ouvert local');return}catch(e){return msg('Mot de passe incorrect')}}try{await pull(false);return}catch(e){}app=fresh();await saveLocal();open('Coffre créé depuis data.js')}
function open(t){$('#lock').classList.add('hide');state(t);render()}
async function openLocal(){pass=$('#pass').value;try{let raw=localStorage.getItem(LK);if(!raw)throw Error('Aucun coffre local. Clique sur Démarrer.');app=await dec(JSON.parse(raw),pass);open('Ouvert local')}catch(e){msg(e.message)}}
async function create(){pass=$('#pass').value;if(!pass)return msg('Mot de passe requis');app=fresh();await saveLocal();open('Créé localement')}
async function ghGet(){let c=cfg();saveCfg();let r=await fetch(`https://api.github.com/repos/${c.owner}/${c.repo}/contents/${c.path}?ref=${c.branch}`,{headers:{Authorization:'Bearer '+c.token,Accept:'application/vnd.github+json'}});if(r.status==404)return null;if(!r.ok)throw Error('GitHub lecture '+r.status+' '+await r.text());return r.json()}
async function pull(alertOn=true){pass=$('#pass').value||pass;if(!pass)throw Error('Mot de passe requis');try{let f=await ghGet();if(!f)throw Error('Aucun coffre distant');let v=JSON.parse(decodeURIComponent(escape(atob(f.content.replace(/\n/g,'')))));app=await dec(v,pass);localStorage.setItem(LK,JSON.stringify(v));await saveLocal();open('Chargé depuis GitHub')}catch(e){if(alertOn){msg(e.message);alert(e.message)}throw e}}
async function push(){try{if(!app)throw Error('Aucune donnée ouverte');let c=cfg(),v=await enc(app,pass),old=await ghGet().catch(e=>null),body={message:'Budget sync '+new Date().toISOString(),content:btoa(unescape(encodeURIComponent(JSON.stringify(v,null,2)))),branch:c.branch};if(old?.sha)body.sha=old.sha;let r=await fetch(`https://api.github.com/repos/${c.owner}/${c.repo}/contents/${c.path}`,{method:'PUT',headers:{Authorization:'Bearer '+c.token,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('GitHub écriture '+r.status+' '+await r.text());state('GitHub synchronisé');alert('Synchronisé dans GitHub')}catch(e){alert(e.message)}}
function man(r){let a=n(r.amount);return r.frequency=='annual'||r.frequency=='oneoff'?a/12:a}
function val(r,stack=[]){if(r.formula){try{return formula(r,stack)}catch(e){r.formulaError=e.message;return man(r)}}return man(r)}
function formula(r,stack=[]){let id=r.id||r.label;if(stack.includes(id))throw Error('Référence circulaire');let all=rows(),ligne=name=>{let s=String(name).toLowerCase(),x=all.find(a=>String(a.label).toLowerCase()==s)||all.find(a=>String(a.label).toLowerCase().includes(s));return x?val(x,[...stack,id]):0},max=Math.max,min=Math.min,round=(x,d=0)=>Number(Number(x).toFixed(d)),mround=(x,m=1)=>Math.round(x/m)*m,vars=r.variables||{},names=Object.keys(vars);let out=new Function(...names,'ligne','max','min','round','mround','return Number('+r.formula+')')(...names.map(k=>vars[k]),ligne,max,min,round,mround);if(!Number.isFinite(out))throw Error('Résultat non numérique');r.formulaError='';return out}
function calc(){let rev={Laura:0,Romain:0},tax={Laura:0,Romain:0},pers={Laura:0,Romain:0},com={},post={},cnt={active:0,Dépense:0,formules:0};for(let r of rows().filter(x=>x.enabled!==false)){cnt.active++;let a=val(r),o=r.owner||'Commun',acc=r.account||'Sans compte';if(r.formula)cnt.formules++;if(r.type=='Revenu'){if(o=='Laura'||o=='Romain')rev[o]+=a;else{com[acc]??={rev:0,dep:0};com[acc].rev+=a}}else if(r.type=='Impôt'){if(o=='Laura'||o=='Romain')tax[o]+=a;else{com[acc]??={rev:0,dep:0};com[acc].dep+=a}}else{cnt.Dépense++;if(o=='Laura'||o=='Romain')pers[o]+=a;else{com[acc]??={rev:0,dep:0};com[acc].dep+=a}post[r.poste||'Sans poste']=(post[r.poste||'Sans poste']||0)+a}}let ref={Laura:rev.Laura-tax.Laura,Romain:rev.Romain-tax.Romain},tot=ref.Laura+ref.Romain,rat={Laura:tot?ref.Laura/tot:.5,Romain:tot?ref.Romain/tot:.5},need={},needT=0;Object.entries(com).forEach(([k,v])=>{let x=v.dep-v.rev;need[k]=x;if(x>0)needT+=x});let out={Laura:needT*rat.Laura+pers.Laura,Romain:needT*rat.Romain+pers.Romain},remain={Laura:ref.Laura-out.Laura,Romain:ref.Romain-out.Romain};return{ref,rat,need,needT,out,remain,post,cnt}}
function line(t,s,a,p){return`<div class=line><div class=ltop><div><div class=lt>${esc(t)}</div><div class=ls>${esc(s||'')}</div></div><div class=amount>${a}</div></div>${p==null?'':`<div class=bar><span style="width:${Math.max(3,Math.min(100,p))}%"></span></div>`}</div>`}
function kpi(t,v,s){return`<article class=kpi><div class=t>${t}</div><div class=v>${v}</div><div class=s>${s||''}</div></article>`}
function render(){let c=calc();$('#remain').textContent=eur(c.remain.Laura+c.remain.Romain);$('#remainSub').textContent=`Laura ${eur(c.remain.Laura)} · Romain ${eur(c.remain.Romain)}`;$('#kpis').innerHTML=[kpi('Laura',eur(c.ref.Laura),(c.rat.Laura*100).toFixed(1)+' %'),kpi('Romain',eur(c.ref.Romain),(c.rat.Romain*100).toFixed(1)+' %'),kpi('Commun net',eur(c.needT),'à alimenter'),kpi('Formules',c.cnt.formules,c.cnt.active+' lignes')].join('');$('#scenario').innerHTML=Object.keys(app.scenarios).map(x=>`<option ${x==app.active?'selected':''}>${esc(x)}</option>`).join('');renderLines();renderAcc(c);renderTop(c);lists()}
function renderAcc(c){let a=Object.entries(c.need).map(([account,need])=>({account,need})).sort((x,y)=>Math.abs(y.need)-Math.abs(x.need)),mx=Math.max(1,...a.map(x=>Math.abs(x.need)));$('#accountsList').innerHTML=a.map(x=>line(x.account,`Laura ${eur(Math.max(0,x.need)*c.rat.Laura)} · Romain ${eur(Math.max(0,x.need)*c.rat.Romain)}`,eur(x.need),Math.abs(x.need)/mx*100)).join('');$('#contrib').innerHTML=[line('Laura','commun + perso',eur(c.out.Laura),null),line('Romain','commun + perso',eur(c.out.Romain),null)].join('')}
function renderTop(c){let all=Object.entries(c.post).map(([poste,amount])=>({poste,amount})).sort((a,b)=>b.amount-a.amount),mx=Math.max(1,...all.map(x=>x.amount));$('#top').innerHTML=all.slice(0,7).map(x=>line(x.poste,'mensuel',eur(x.amount),x.amount/mx*100)).join('');let al=[];Object.entries(c.need).forEach(([k,v])=>{if(v>1000)al.push(line(k,'besoin élevé',eur(v),50));if(v<0)al.push(line(k,'excédent',eur(v),50))});rows().filter(r=>r.formulaError).slice(0,5).forEach(r=>al.push(line(r.label,'Erreur formule : '+r.formulaError,'!',null)));$('#alerts').innerHTML=al.join('')||line('Aucune alerte forte','budget cohérent','OK',null)}
function ico(r){let s=((r.poste||'')+' '+(r.label||'')).toLowerCase();if(s.includes('salaire'))return'€';if(s.includes('pret')||s.includes('taxe'))return'⌂';if(s.includes('garde')||s.includes('rachel')||s.includes('charlie'))return'👶';if(s.includes('voiture'))return'🚗';if(s.includes('course'))return'🛒';if(s.includes('lmnp'))return'🏘';return'•'}
function filt(){let q=filters.q.toLowerCase();return rows().map((r,i)=>({r,i})).filter(({r})=>(filters.owner=='Tous'||r.owner==filters.owner)&&(filters.type=='Tous'||r.type==filters.type)&&(!q||[r.poste,r.label,r.account,r.owner,r.type,r.formula?'formule':''].join(' ').toLowerCase().includes(q)))}
function badge(c,t){return`<span class="badge ${c}">${esc(t)}</span>`}
function renderLines(){$('#list').innerHTML=filt().map(({r,i})=>`<article class="tx ${r.enabled===false?'off':''}"><div class=txm><div class=av>${ico(r)}</div><div><div class=tt>${esc(r.label||r.poste)}</div><div class=ls>${esc(r.poste||'Sans poste')} · ${esc(r.account||'Sans compte')}</div><div class=meta>${badge(r.type=='Revenu'?'rev':r.type=='Impôt'?'tax':'dep',r.type)}${badge('own',r.owner||'Commun')}${r.formula?badge('calc','Formule'):''}</div></div><div class=amount>${eur(val(r))}</div></div><div class=txa><button data-tog=${i}>${r.enabled===false?'Activer':'Désactiver'}</button><button data-ed=${i}>Modifier</button></div></article>`).join('')||line('Aucune ligne','change les filtres','-',null)}
function lists(){let p=[...new Set(rows().map(r=>r.poste).filter(Boolean))].sort(),a=[...new Set(rows().map(r=>r.account).filter(Boolean))].sort();$('#postes').innerHTML=p.map(x=>`<option value="${esc(x)}"></option>`).join('');$('#accountsData').innerHTML=a.map(x=>`<option value="${esc(x)}"></option>`).join('')}
function openEdit(i=null){edit=i;let r=i==null?{type:'Dépense',owner:'Commun',amount:0,account:'CERA Joint',poste:'Nouveau poste',label:'',enabled:true,frequency:'monthly',formula:'',variables:{},note:''}:rows()[i];$('#editTitle').textContent=i==null?'Ajouter':'Modifier';for(let [id,v] of [['fType',r.type||'Dépense'],['fOwner',r.owner||'Commun'],['fAmount',String(r.amount??0).replace('.',',')],['fAccount',r.account||'CERA Joint'],['fPoste',r.poste||''],['fLabel',r.label||''],['fFreq',r.frequency||'monthly'],['fFormula',r.formula||''],['fVars',JSON.stringify(r.variables||{},null,2)],['fNote',r.note||'']])$('#'+id).value=v;$('#fEnabled').checked=r.enabled!==false;$('#del').style.display=i==null?'none':'block';$('#copy').style.display=i==null?'none':'block';preview();$('#edit').showModal()}
function form(){let vars={};try{vars=$('#fVars').value.trim()?JSON.parse($('#fVars').value):{}}catch(e){throw Error('Variables JSON invalides')}return{type:$('#fType').value,owner:$('#fOwner').value,amount:n($('#fAmount').value),account:$('#fAccount').value.trim()||'CERA Joint',poste:$('#fPoste').value.trim()||'Sans poste',label:$('#fLabel').value.trim()||$('#fPoste').value.trim()||'Sans libellé',frequency:$('#fFreq').value,formula:$('#fFormula').value.trim(),variables:vars,note:$('#fNote').value.trim(),enabled:$('#fEnabled').checked}}
function preview(){try{$('#formulaPreview').textContent='Montant calculé : '+eur(val(form()))}catch(e){$('#formulaPreview').textContent='Erreur : '+e.message}}
function go(s){$$('nav button').forEach(b=>b.classList.toggle('on',b.dataset.go==s));$$('.screen').forEach(x=>x.classList.toggle('on',x.id==s));$('#title').textContent={home:'Synthèse',lines:'Lignes',accounts:'Comptes',more:'Plus'}[s]||'Budget'}
$$('nav button').forEach(x=>x.onclick=()=>go(x.dataset.go));$('#start').onclick=start;$('#openLocal').onclick=openLocal;$('#create').onclick=create;$('#pull').onclick=()=>pull(true);$('#pull2').onclick=()=>pull(true);$('#push').onclick=push;$('#add').onclick=()=>openEdit();
$('#list').onclick=e=>{let ed=e.target.closest('[data-ed]'),tg=e.target.closest('[data-tog]');if(ed)openEdit(+ed.dataset.ed);if(tg){rows()[+tg.dataset.tog].enabled=rows()[+tg.dataset.tog].enabled===false;auto();render()}};
$('#ok').onclick=()=>{try{let v=form();if(edit==null)rows().unshift(v);else rows()[edit]={...rows()[edit],...v};$('#edit').close();auto();render()}catch(e){alert(e.message)}};
$('#copy').onclick=()=>{if(edit!=null)rows().unshift({...rows()[edit],label:rows()[edit].label+' - copie'});$('#edit').close();auto();render()};
$('#del').onclick=()=>{if(edit!=null&&confirm('Supprimer ?')){rows().splice(edit,1);$('#edit').close();auto();render()}};
['fFormula','fVars','fAmount','fFreq'].forEach(id=>$('#'+id).addEventListener('input',preview));$('#q').oninput=e=>{filters.q=e.target.value;renderLines()};
$$('[data-owner]').forEach(x=>x.onclick=()=>{$$('[data-owner]').forEach(b=>b.classList.remove('on'));x.classList.add('on');filters.owner=x.dataset.owner;renderLines()});$$('[data-type]').forEach(x=>x.onclick=()=>{$$('[data-type]').forEach(b=>b.classList.remove('on'));x.classList.add('on');filters.type=x.dataset.type;renderLines()});
$('#scenario').onchange=e=>{app.active=e.target.value;auto();render()};$('#newSc').onclick=$('#dupSc').onclick=()=>{let name=prompt('Nom du scénario','Hypothèse');if(!name)return;app.scenarios[name]={createdAt:new Date().toISOString(),transactions:JSON.parse(JSON.stringify(rows()))};app.active=name;auto();render()};
$('#renSc').onclick=()=>{let name=prompt('Nouveau nom',app.active);if(!name)return;app.scenarios[name]=app.scenarios[app.active];delete app.scenarios[app.active];app.active=name;auto();render()};$('#delSc').onclick=()=>{if(Object.keys(app.scenarios).length<2)return alert('Garde au moins un scénario');if(confirm('Supprimer ?')){delete app.scenarios[app.active];app.active=Object.keys(app.scenarios)[0];auto();render()}};
$('#save').onclick=saveLocal;$('#showFormulaLines').onclick=()=>{go('lines');filters.q='formule';$('#q').value='formule';renderLines()};$('#config').onclick=()=>{$('#lock').classList.remove('hide');msg('Modifie les paramètres puis clique sur Démarrer.')};$('#forget').onclick=()=>{let c=JSON.parse(localStorage.getItem(CK)||'{}');delete c.token;localStorage.setItem(CK,JSON.stringify(c));$('#token').value='';alert('Token local effacé')};
$('#exportClear').onclick=()=>download(JSON.stringify(app,null,2),'budget_2026_clair.json');$('#exportCrypt').onclick=async()=>download(JSON.stringify(await enc(app,pass),null,2),'budget_2026_chiffre.json');function download(s,n){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'application/json'}));a.download=n;a.click();URL.revokeObjectURL(a.href)}
loadCfg();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));