(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],M=['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Août','Sep','Oct','Nov','Déc'];
const eur=v=>(Number(v)||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}),num=v=>Number(String(v??0).replace(',','.'))||0,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let month=new Date().getMonth()+1,editI=null;
function rowsSafe(){try{return rows()}catch(e){return[]}}function v(r){try{return Math.abs(val(r))}catch(e){return Math.abs(num(r.amount))}}function save(){try{saveLocal()}catch(e){}try{auto()}catch(e){}}
function init(){document.body.classList.add('v12product','v10dark','v9');if(!$('#v12ProductCss')){let l=document.createElement('link');l.id='v12ProductCss';l.rel='stylesheet';l.href='v12-product.css?v=1';document.head.appendChild(l)}$$('.versionTag').forEach(x=>x.textContent='V12 Product · lignes simples')}
function typ(r){let t=String(r.type||'').toLowerCase();if(t.includes('revenu'))return'income';if(t.includes('imp'))return'tax';return'expense'}
function cad(r){return r.cadence||(r.frequency==='annual'?'yearly':r.frequency==='oneoff'?'oneOff':'monthly')}
function inferMonth(r){let s=String([r.label,r.poste,r.note].join(' ')).toLowerCase();if(s.includes('octobre')||s.includes('fonci'))return 10;if(s.includes('vacance')||s.includes('aout')||s.includes('août'))return 8;if(s.includes('noel')||s.includes('noël'))return 12;return Number(r.paymentMonth||r.month||1)}
function amount(r){let c=cad(r),m=v(r),raw=Math.abs(num(r.amount));if(c==='monthly')return m||raw;if(c==='yearly'||c==='oneOff')return Math.abs(num(r.annualAmount)||raw||m*12);return raw||m}
function months(r){let c=cad(r);if(c==='monthly')return Array.from({length:12},(_,i)=>i+1);if(c==='quarterly')return[3,6,9,12];if(c==='customMonths'&&Array.isArray(r.months)&&r.months.length)return r.months.map(Number);return[inferMonth(r)]}
function impacts(r){let a=Array(12).fill(0),amt=amount(r);months(r).forEach(m=>{if(m>=1&&m<=12)a[m-1]+=amt});return a}
function forecast(){let f={inc:Array(12).fill(0),out:Array(12).fill(0),tax:Array(12).fill(0),acc:{},items:Array.from({length:12},()=>[])};rowsSafe().filter(r=>r.enabled!==false).forEach((r,i)=>{let t=typ(r),im=impacts(r);im.forEach((x,m)=>{if(!x)return;if(t==='income')f.inc[m]+=x;else{if(t==='tax')f.tax[m]+=x;f.out[m]+=x;let a=r.account||'Compte non défini';(f.acc[a]||(f.acc[a]=Array(12).fill(0)))[m]+=x}f.items[m].push({r,i,t,x})})});f.rem=f.inc.map((x,i)=>x-f.out[i]);return f}
function sections(){let main=$('main');if(!main)return;if(!$('#forecast'))main.insertAdjacentHTML('beforeend','<section id="forecast" class="screen"><div class="v12SectionHead"><div><h2>Prévision 12 mois</h2><p>Visualiser les pics et les mois atypiques.</p></div><span class="v12Pill">Réel</span></div><div id="v12Forecast"></div></section>');if(!$('#transfers'))main.insertAdjacentHTML('beforeend','<section id="transfers" class="screen"><div class="v12SectionHead"><div><h2>Virements</h2><p>Combien virer, vers quels comptes et pourquoi.</p></div><span class="v12Pill">Mensuel</span></div><div id="v12Transfers"></div></section>')}
function show(id){$$('.screen').forEach(s=>s.classList.toggle('on',s.id===id));$$('nav button').forEach(b=>b.classList.toggle('on',b.dataset.go===id));let h=$('#title');if(h)h.textContent={home:'Synthèse',lines:'Lignes',forecast:'Prévision',transfers:'Virements',more:'Plus'}[id]||'Budget';render()}
function nav(){let n=$('nav');if(!n||n.dataset.v12)return;n.dataset.v12=1;n.innerHTML='<button data-go="home" class="on"><span class="navIcon">⌂</span><span class="navLabel">Accueil</span></button><button data-go="lines"><span class="navIcon">☰</span><span class="navLabel">Lignes</span></button><button data-go="forecast"><span class="navIcon">▥</span><span class="navLabel">Prévision</span></button><button data-go="transfers"><span class="navIcon">⇄</span><span class="navLabel">Virements</span></button><button data-go="more"><span class="navIcon">•••</span><span class="navLabel">Plus</span></button>';$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.go))}
function home(){let h=$('#home');if(!h)return;let f=forecast(),i=month-1;if(!$('#v12Home'))h.insertAdjacentHTML('afterbegin','<section id="v12Home" class="v12Home"></section>');$('#v12Home').innerHTML=`<article class="v12Hero"><small>Reste prévisionnel ${M[i]}</small><strong>${eur(f.rem[i])}</strong><span>Revenus ${eur(f.inc[i])} · sorties ${eur(f.out[i])}</span></article><div class="v12Quick"><div class="v12Mini"><small>Virements</small><strong>${eur(f.out[i])}</strong></div><div class="v12Mini"><small>Impôts</small><strong>${eur(f.tax[i])}</strong></div></div>`}
function lineCard(r,i){let t=typ(r),c=cad(r),nm=months(r).find(m=>m>=month)||months(r)[0]||1,sign=t==='income'?'+':'-';return`<article class="v12Card ${t}" data-open-line="${i}"><div class="v12CardTop"><div class="v12Icon">${t==='income'?'↓':t==='tax'?'%':'↑'}</div><div class="v12Title"><small>${t==='income'?'Revenu':t==='tax'?'Impôt':'Dépense'}</small><h3>${esc(r.label||r.poste)}</h3><p>${esc(r.account||'Sans compte')} · ${esc(r.owner||'Commun')}</p></div><div class="v12Amount"><strong>${sign}${eur(amount(r))}</strong><span>${c==='monthly'?'mensuel':c==='yearly'?'annuel':c==='oneOff'?'ponctuel':'variable'}</span></div></div><div class="v12Meta"><span>${esc(r.poste||'Sans catégorie')}</span><span class="next">Prochain : ${M[nm-1]}</span><span class="real">Annuel : ${eur(impacts(r).reduce((a,b)=>a+b,0))}</span></div><div class="v12Actions"><button data-toggle-line="${i}">${r.enabled===false?'Activer':'Désactiver'}</button><button data-edit-line="${i}">Modifier</button></div></article>`}
function lines(){let l=$('#list');if(!l)return;let q=String($('#q')?.value||'').toLowerCase();let a=rowsSafe().map((r,i)=>({r,i})).filter(x=>!q||String([x.r.label,x.r.poste,x.r.account,x.r.owner].join(' ')).toLowerCase().includes(q));l.className='v12LineList';l.innerHTML=a.map(x=>lineCard(x.r,x.i)).join('')||'<div class="v9Empty">Aucune ligne</div>';let c=$('#lineCount');if(c)c.textContent=a.length+' lignes'}
function chart(){let el=$('#v12Forecast');if(!el)return;let f=forecast(),max=Math.max(1,...f.out),i=month-1;let bars=M.map((m,k)=>`<div class="v12MonthBar ${k===i?'on':''}"><div class="v12BarStack"><div class="v12Bar ${f.tax[k]>0?'tax':''}" style="height:${Math.max(4,f.out[k]/max*150)}px"></div></div><button data-month="${k+1}">${m}</button></div>`).join('');let detail=f.items[i].sort((a,b)=>b.x-a.x).slice(0,10).map(x=>`<div class="v12Row"><div><b>${esc(x.r.label||x.r.poste)}</b><br><span>${esc(x.r.account||'Sans compte')}</span></div><strong>${x.t==='income'?'+':'-'}${eur(x.x)}</strong></div>`).join('');el.innerHTML=`<div class="v12ForecastGrid"><article class="v12ForecastCard"><small>Besoin de virement</small><div class="v12Chart">${bars}</div><div class="v12MonthDetail"><h3>${M[i]} · ${eur(f.out[i])} à prévoir</h3></div></article><article class="v12ForecastCard"><small>Détail du mois</small><div class="v12Rows">${detail||'<div class="v12Row"><b>Aucune ligne</b></div>'}</div></article></div>`}
function transfers(){let el=$('#v12Transfers');if(!el)return;let f=forecast(),i=month-1,acc=Object.entries(f.acc).map(([a,v])=>({a,v:v[i]})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v),total=acc.reduce((s,x)=>s+x.v,0);el.innerHTML=`<article class="v12Hero"><small>${M[i]} · total à virer</small><strong>${eur(total)}</strong><span>Montants réels du mois</span></article><div style="height:12px"></div>${acc.map(x=>`<article class="v12TransferAccount"><h3>${esc(x.a)}</h3><div class="big">${eur(x.v)}</div></article>`).join('')||'<div class="v9Empty">Aucun virement ce mois</div>'}`}
function editUI(i=editI){let r=rowsSafe()[i];if(!r)return;['#fFormula','#fVars','#formulaPreview'].forEach(s=>{let e=$(s),p=e?.closest('label')||e;if(p)p.classList.add('v12HiddenTech')});let freq=$('#fFreq')?.closest('label');if(freq)freq.classList.add('v12HiddenTech');if(r.formula){$('#fAmount').value=String(v(r)).replace('.',',');$('#fFormula').value='';$('#fVars').value='{}'}if(!$('#v12LineEditor'))($('#formulaPreview')||$('#fType')?.closest('.grid2')).insertAdjacentHTML('beforebegin','<section id="v12LineEditor" class="v12LineEditor"><h3>Fréquence & échéance</h3><p>Décris quand cette ligne impacte réellement le budget.</p><div class="v12EditGrid"><label>Fréquence<select id="v12Cadence"><option value="monthly">Tous les mois</option><option value="yearly">Une fois par an</option><option value="oneOff">Une fois seulement</option><option value="quarterly">Tous les trimestres</option></select></label><label>Mois<select id="v12PaymentMonth"></select></label><div class="v12PreviewLine"><span>Impact annuel</span><strong id="v12ImpactPreview">-</strong></div></div></section>');let pm=$('#v12PaymentMonth');if(pm&&!pm.children.length)pm.innerHTML=M.map((m,i)=>`<option value="${i+1}">${m}</option>`).join('');$('#v12Cadence').value=cad(r);pm.value=inferMonth(r);editPreview()}
function editPreview(){let c=$('#v12Cadence')?.value||'monthly',a=Math.abs(num($('#fAmount')?.value)),annual=c==='monthly'?a*12:c==='quarterly'?a*4:a;let p=$('#v12ImpactPreview');if(p)p.textContent=eur(annual);let f=$('#fFreq');if(f)f.value=c==='yearly'?'annual':c==='oneOff'?'oneoff':'monthly'}
function syncEdit(){let r=rowsSafe()[editI];if(!r)return;r.cadence=$('#v12Cadence')?.value||'monthly';r.frequency=r.cadence==='yearly'?'annual':r.cadence==='oneOff'?'oneoff':'monthly';r.paymentMonth=Number($('#v12PaymentMonth')?.value||1);r.formula='';r.variables={};save();setTimeout(render,100)}
function render(){init();sections();nav();home();lines();chart();transfers();$$('.v9FormulaBox,#formulaAudit,#v10Profiles,.v10FormulaWizard,.v12Calc').forEach(e=>e.style.display='none')}
document.addEventListener('click',e=>{let b=e.target.closest('[data-edit-line],[data-open-line],[data-ed],[data-v9-open]');if(b){editI=Number(b.dataset.editLine??b.dataset.openLine??b.dataset.ed??b.dataset.v9Open);if((b.dataset.editLine||b.dataset.openLine)&&typeof openEdit==='function')openEdit(editI);setTimeout(()=>editUI(editI),120)}let t=e.target.closest('[data-toggle-line]');if(t){let r=rowsSafe()[Number(t.dataset.toggleLine)];if(r){r.enabled=r.enabled===false;save();render()}}let m=e.target.closest('[data-month]');if(m){month=Number(m.dataset.month);render()}if(e.target.id==='ok')setTimeout(syncEdit,100)},true);
document.addEventListener('input',e=>{if(e.target.matches('#q'))setTimeout(lines,80);if(e.target.closest('#v12LineEditor')||e.target.matches('#fAmount'))editPreview()});document.addEventListener('change',e=>{if(e.target.closest('#v12LineEditor'))editPreview()});
setInterval(render,1800);addEventListener('load',()=>setTimeout(render,800));if(document.readyState!=='loading')setTimeout(render,600);
})();
